import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Inspector } from "@/components/Inspector";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Sync HTML class when theme changes (for API-based theme updates)
              (function() {
                // Listen for theme change messages
                window.addEventListener('message', function(event) {
                  if (event.data?.type === 'THEME_CHANGED' || event.data?.type === 'theme-change') {
                    const theme = event.data.theme || event.data.themeName;
                    if (theme === 'dark' || theme === 'light') {
                      document.documentElement.classList.remove('dark', 'light');
                      document.documentElement.classList.add(theme);
                    }
                  }
                });
                
                // Also watch for globals.css changes and sync class
                let lastTheme = localStorage.getItem('theme') || 'light';
                const observer = new MutationObserver(function() {
                  const currentTheme = document.documentElement.classList.contains('dark') ? 'dark' : 'light';
                  if (currentTheme !== lastTheme) {
                    lastTheme = currentTheme;
                    localStorage.setItem('theme', currentTheme);
                  }
                });
                observer.observe(document.documentElement, {
                  attributes: true,
                  attributeFilter: ['class']
                });
                
                // Restore theme from localStorage on load
                const savedTheme = localStorage.getItem('theme');
                if (savedTheme && (savedTheme === 'dark' || savedTheme === 'light')) {
                  document.documentElement.classList.remove('dark', 'light');
                  document.documentElement.classList.add(savedTheme);
                }
                
                // Fallback: Detect theme from CSS variables
                function detectThemeFromCSS() {
                  try {
                    const computed = getComputedStyle(document.documentElement);
                    const bgColor = computed.getPropertyValue('--background').trim();
                    // Dark theme typically has darker background values
                    // Check if background is dark (oklch with low lightness)
                    let isDark = false;
                    if (bgColor.includes('oklch')) {
                      const match = bgColor.match(/oklch\(([\d.]+)/);
                      if (match && match[1]) {
                        isDark = parseFloat(match[1]) < 0.5;
                      }
                    }
                    
                    const detectedTheme = isDark ? 'dark' : 'light';
                    const currentTheme = document.documentElement.classList.contains('dark') ? 'dark' : 'light';
                    
                    if (detectedTheme !== currentTheme) {
                      document.documentElement.classList.remove('dark', 'light');
                      document.documentElement.classList.add(detectedTheme);
                      localStorage.setItem('theme', detectedTheme);
                    }
                  } catch (e) {
                    // Silently fail
                  }
                }
                
                // Force reload CSS when globals.css is updated (for API-based updates)
                let cssReloaded = false;
                function reloadCSS() {
                  if (cssReloaded) return;
                  cssReloaded = true;
                  const links = document.querySelectorAll('link[rel="stylesheet"]');
                  links.forEach(function(link) {
                    const href = link.getAttribute('href');
                    if (href && href.includes('globals.css')) {
                      const newHref = href.split('?')[0] + '?t=' + Date.now();
                      link.setAttribute('href', newHref);
                      // Detect theme after CSS loads
                      link.onload = function() {
                        setTimeout(detectThemeFromCSS, 50);
                      };
                    }
                  });
                  setTimeout(function() { 
                    cssReloaded = false;
                    detectThemeFromCSS();
                  }, 1000);
                }
                
                // Listen for CSS update messages
                window.addEventListener('message', function(event) {
                  if (event.data?.type === 'CSS_UPDATED' || event.data?.type === 'globals-css-updated') {
                    reloadCSS();
                    // Also update theme class if provided
                    if (event.data.theme) {
                      const theme = event.data.theme === 'dark' ? 'dark' : 'light';
                      document.documentElement.classList.remove('dark', 'light');
                      document.documentElement.classList.add(theme);
                      localStorage.setItem('theme', theme);
                    } else {
                      // If no theme provided, detect it from CSS
                      setTimeout(detectThemeFromCSS, 200);
                    }
                  }

                  // Listen for instant theme preview (full theme palette)
                  if (event.data?.type === 'APPLY_THEME_PREVIEW') {
                    var theme = event.data.theme;
                    if (!theme) return;

                    // Remove old preview style if exists
                    var oldStyle = document.getElementById('theme-preview-override');
                    if (oldStyle) oldStyle.remove();

                    // Inject new style that overrides all CSS variables
                    var style = document.createElement('style');
                    style.id = 'theme-preview-override';
                    style.textContent =
                      ':root, .dark, .light {' +
                      '  --background: ' + (theme.background || '') + ' !important;' +
                      '  --foreground: ' + (theme.foreground || '') + ' !important;' +
                      '  --card: ' + (theme.card || '') + ' !important;' +
                      '  --card-foreground: ' + (theme.cardForeground || '') + ' !important;' +
                      '  --popover: ' + (theme.popover || '') + ' !important;' +
                      '  --popover-foreground: ' + (theme.popoverForeground || '') + ' !important;' +
                      '  --primary: ' + (theme.primary || '') + ' !important;' +
                      '  --primary-foreground: ' + (theme.primaryForeground || '') + ' !important;' +
                      '  --secondary: ' + (theme.secondary || '') + ' !important;' +
                      '  --secondary-foreground: ' + (theme.secondaryForeground || '') + ' !important;' +
                      '  --muted: ' + (theme.muted || '') + ' !important;' +
                      '  --muted-foreground: ' + (theme.mutedForeground || '') + ' !important;' +
                      '  --accent: ' + (theme.accent || '') + ' !important;' +
                      '  --accent-foreground: ' + (theme.accentForeground || '') + ' !important;' +
                      '  --destructive: ' + (theme.destructive || '') + ' !important;' +
                      '  --border: ' + (theme.border || '') + ' !important;' +
                      '  --input: ' + (theme.input || '') + ' !important;' +
                      '  --ring: ' + (theme.ring || '') + ' !important;' +
                      '  --chart-1: ' + (theme.chart1 || '') + ' !important;' +
                      '  --chart-2: ' + (theme.chart2 || '') + ' !important;' +
                      '  --chart-3: ' + (theme.chart3 || '') + ' !important;' +
                      '  --chart-4: ' + (theme.chart4 || '') + ' !important;' +
                      '  --chart-5: ' + (theme.chart5 || '') + ' !important;' +
                      '  --sidebar: ' + (theme.sidebar || '') + ' !important;' +
                      '  --sidebar-foreground: ' + (theme.sidebarForeground || '') + ' !important;' +
                      '  --sidebar-primary: ' + (theme.sidebarPrimary || '') + ' !important;' +
                      '  --sidebar-primary-foreground: ' + (theme.sidebarPrimaryForeground || '') + ' !important;' +
                      '  --sidebar-accent: ' + (theme.sidebarAccent || '') + ' !important;' +
                      '  --sidebar-accent-foreground: ' + (theme.sidebarAccentForeground || '') + ' !important;' +
                      '  --sidebar-border: ' + (theme.sidebarBorder || '') + ' !important;' +
                      '  --sidebar-ring: ' + (theme.sidebarRing || '') + ' !important;' +
                      '}';
                    document.head.appendChild(style);

                    // Notify parent that theme preview was applied
                    window.parent.postMessage({
                      type: 'THEME_PREVIEW_APPLIED',
                      themeName: event.data.themeName || 'custom'
                    }, '*');
                  }

                  // Listen for clearing theme preview (when persisted theme is applied)
                  if (event.data?.type === 'CLEAR_THEME_PREVIEW') {
                    var oldStyle = document.getElementById('theme-preview-override');
                    if (oldStyle) oldStyle.remove();
                  }
                });
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
        </ThemeProvider>
        <Inspector />
      </body>
    </html>
  );
}